/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WebScraper;

import java.util.List;

public class App {
    public static void main(String[] args) {

        /*List<ParkingBay> pbs = Scrape.getListOfParkingBays();
        pbs.forEach(System.out::println);
        System.out.println(pbs.size());*/

        FileManager fm = new FileManager();
        fm.startUp();
        fm.getListOfParkingBays().forEach(System.out::println);

        System.out.println("next");
        System.out.println("_____------_____");
        MapFunctions.sortByClosest(fm.getListOfParkingBays(), 50.816255435206465, -0.1069777495032263).forEach(System.out::println);

    }
}
